# Web Config
server:
  address: 0.0.0.0
  port: 50001

# Spring Config
spring:
  application:
    name: rainy-gateway
  cloud:
    # gateway 配置
    gateway:
      # Netty Http Client 配置
      httpclient:
        # 连接下游服务超时时间
        connect-timeout: 10
        # 响应超时时间
        response-timeout: 10s
        # 开启压缩
        compression: true
        # 最大响应头大小
        max-header-size: 4096
        # 连接池
        pool:
          type: elastic
      # 跨域处理
      global-cors:
        cors-configurations:
          '[/**]': #匹配所有path请求
            allowedOriginPatterns: "*" #允许域名访问
            allowed-headers: "*"
            allow-credentials: true
            #允许的请求方式GET,POST,PUT,DELETE
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      # 服务路由映射
      routes:
        - id: sample
          uri: lb://rainy-sample
#          uri: http://127.0.0.1:11001
          # 谓词匹配链
          predicates:
            # 路由匹配前缀
            - Path=/api-sample/**
          # 过滤器链
          filters:
            # 去除 path 首个前缀
            - StripPrefix=1