# 开发环境配置
spring:
  # 数据源配置
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/rainy?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root
    # 连接池
    hikari:
      minimum-idle: 10      # 最小连接数
      maximum-pool-size: 64 # 最大连接数
      idle-timeout: 600000  # 空闲连接超时时间
      connection-timeout: 30000 # 连接超时时间
      max-lifetime: 1800000     # 连接最大生命周期

  cloud:
    # 服务注册中心
    nacos:
      discovery:
        server-addr: 192.168.95.130:8848
        group: rainy-dev
        namespace: 910a91d6-39cc-4677-8ce9-d320846a36c7
grpc:
  # 服务端配置
  server:
    # 最大传输数据大小，默认为 Integer.MAX_VALUE。-1 表示不上限
    max-inbound-message-size: 4194304
    # 最大传输的元数据大小
    max-inbound-metadata-size: 4096
    # 开启keep-alive
    enable-keep-alive: true
    port: 12002
  # 客户端配置
  client:
    GLOBAL:
      negotiation-type: plaintext
      enable-keep-alive: true
      max-inbound-message-size: 4194304
      max-inbound-metadata-size: 4096
      keep-alive-without-calls: true